# Generated by Django 4.0.5 on 2022-06-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='msg_receciver',
            new_name='msg_receiver',
        ),
    ]
